### ISSUE TITLE
Netherite kitchen knifes are not fireproof

### ISSUE THREAD

**Issue by haykam821** [FoundationGames/Sandwichable#101]
Unlike other netherite tools, netherite kitchen knifes are not fireproof.

**Comment by FoundationGames** [comment]
Will be fixed, this is an incredibly important and breaking issue

**Comment by Reeses-Puffs** [comment]
Maybe fix it in the update for 1.17.1 😳

**Comment by FoundationGames** [comment]
Fixed in 1.2-rc1
