### ISSUE TITLE
[Gameplay Bug] Pickled cucumber duplication when pickle jar is placed on top of a hopper

### ISSUE THREAD

**Issue by derram** [FoundationGames/Sandwichable#104]
**How To Reproduce**
Place pickle jar on top of hopper, hopper fills with cucumbers or pickled cucumbers depending on the state of the jar.

Mod version is v1..2-beta5
Modpack is All Of Fabric 3 - 1.16.5

**Comment by FoundationGames** [comment]
Unable to reproduce this issue, screenshots would help
