### ISSUE TITLE
[Request] make tags for items

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [FoundationGames/Sandwichable#107]
**Description**
Briefly describe here what you think should be added or changed about Sandwichable.
I'm working on making a mod that adds more compatibility between Sandwichable and croptopia and it would be much easier if you used tags. For example I know no way to make croptopias cucumbers act like sandwichables cucumbers when it comes to pickle jars. Croptopia already does this, as i can extend its classes (i.e. add more salts)

**Problem or Reasoning**
Here you can go into detail about why you think this feature or change should be made to Sandwichable.
It would make making extensions for the mod much easier, as you could just make a tag file and know that the recipe will work.
**How it will work**
Explain the mechanics and implications of this feature or change. It's always nice to be detailed.
Instead of directly referencing items you reference tags. This is already used for bread, but I'd like to see it for other items like cucumbers and cultures, as some things are hard to extend.

**Comment by FoundationGames** [comment]
Was added in 1.2, includes croptopia items for compatibility https://github.com/FoundationGames/Sandwichable/tree/indev/src/main/resources/data/c/tags/items

**Comment by TheDrawingCoder-Gamer** [comment]
cool
