### ISSUE TITLE
[Request] AppleSkin 2.0.0+ incompatible with Sandwichable

### ISSUE THREAD

**Issue by ghost** [FoundationGames/Sandwichable#108]
**Description**
- Make compatibility  with Appleskin 2.0.1,

**Problem or Reasoning**
-  Fix incompatibility of both mods
- https://github.com/squeek502/AppleSkin/issues/128

**How it will work**
https://github.com/squeek502/AppleSkin/tree/1.16-fabric#for-mod-developers

Regards,
Igor

**Comment by FoundationGames** [comment]
Thank you for linking AppleSkin's developer section of the readme, last I checked it lacked a proper API

**Comment by ghost** [comment]
No problem, waiting for the compability release
*if there is an uprising, will you say something about?*

**Comment by FoundationGames** [comment]
Fixed in 1.2-rc1

**Comment by i-g0r** [comment]
Not fixed, still crash at start

**Comment by FoundationGames** [comment]
> Not fixed, still crash at start

Please post a crash log
