### ISSUE TITLE
[Gameplay Bug] using with croptopia give wrong seeds for croptopia tomatoes

### ISSUE THREAD

**Issue by yeete183** [FoundationGames/Sandwichable#109]
**Description**
putting croptopia tomato to make seeds instead gives sandwhichable seeds instead of the croptopia seeds

**How To Reproduce**
get croptopia and sandwhichable and put croptopia tomato into crafting grid and will give sandwhichable seeds 

**Expected Behavior**
croptopia tomato to give croptopia seeds

**Media**
![Screenshot 2021-07-24 174007](https://user-images.githubusercontent.com/84253595/126861399-2bcb23cb-d4eb-4d83-862d-c5a051235346.png)
![Screenshot 2021-07-24 174014](https://user-images.githubusercontent.com/84253595/126861401-e1333209-ecac-4b29-8503-c9704f02e9b5.png)

**Comment by FoundationGames** [comment]
fixed in 1.2-rc1
