### ISSUE TITLE
Source is not complete

### ISSUE THREAD

**Issue by halotroop2288** [FoundationGames/Sandwichable#11]
I have cloned the repository, and it seems to be incomplete. You may not have committed some files, such as CheeseType.java, CheeseRegistry.java, BasinContent.java, etc.

I would like to make changes in my own fork of this mod, but I cannot do so without the full source code.

**Comment by FoundationGames** [comment]
That is very strange! I would recommend that you wait until version 1.1 is released because i have already begun development on that locally. I honestly don't know why those files were not committed

**Comment by FoundationGames** [comment]
1.1 is out, source is now complete again!
