### ISSUE TITLE
[Game CRASH] Game Crashing When Adding Sandwichable

### ISSUE THREAD

**Issue by CodWafer** [FoundationGames/Sandwichable#111]
**Description**
When launching, the game crashes-
I do need to mention, I know sandwitchable is the problem, as this didnt happen untill I added it

**Steps to Reproduce**
Sadly, it would take me too long to list the modlist (I have to go soon) but they are listed in the crash log-
simply install them all and launch the game

**Crash Log**
https://paste.ee/p/h9lf1

**Media**
It just opens minecraft, then immediately closes it. I see a white box, then the box disappears and the launcher opens saying it crashed

(Also sorry, I didn't have much time to make this, and idk what to put the name as)

**Comment by FoundationGames** [comment]
Use a version of appleskin less than 2.0
A fix for this has been on the way for a while
