### ISSUE TITLE
[1.17] Sandwichable awards all four advancements as soon as any item enters the player's inventory.

### ISSUE THREAD

**Issue by dragonmaus** [FoundationGames/Sandwichable#116]
As the title states, when I enter a newly-created world, all four Sandwichable advancements are awarded as soon as I pick up my first item, no matter what kind of item that is.

I am running:
- Minecraft 1.17.1
- Fabric Loader 0.12.4
- Fabric API 0.41.3
- Cloth Config 5.0.38
- Sandwichable 1.2-rc1

Log file: https://gist.github.com/dragonmaus/b5eb857e87c520955ba4ced00d399f16
Screenshots:
![2021-11-04_20 34 51](https://user-images.githubusercontent.com/5817605/140439509-b0b7fa98-f9a1-45f9-89a5-0a8f756a31f7.png)
![2021-11-04_20 34 55](https://user-images.githubusercontent.com/5817605/140439512-281f30d5-dec2-482b-9587-a9e2431ef9d8.png)

**Comment by tankyap** [comment]
bruh I also saw the issue too. I was confused.
