### ISSUE TITLE
Shrub gives shrub itself instead of seeds when break it normally(and some other issues)

### ISSUE THREAD

**Issue by tankyap** [FoundationGames/Sandwichable#118]
> I like how shrub don't gives seeds when breaked with fists, just a shrub.`(did I do it wrong?)`

> And also some of the blocks are hard to break and it drops nothing.

Fabric loader ver: 0.11.7(1.17.1)
Sandwichable mod ver: sandwichable-1.2-rc2+1.17
latest.log: [latest.log](https://github.com/FoundationGames/Sandwichable/files/7531975/latest.log)

**Comment by keriugi** [comment]
the shrub also drops itself instead of seeds for me.

fabric loader 0.12.5, mc version 1.17.1

sandwichable-1.2-rc2+1.17.jar
