### ISSUE TITLE
if a toaster is interacted with non player element, when it finishes toasting a toast, it toasts the server

### ISSUE THREAD

**Issue by SRAZKVT** [FoundationGames/Sandwichable#127]
Whenever a toaster is interacted with non player element, the variable lastUser isn't set to anything, it stays as null, when the toaster finishes toasting it just ends up crashing the server because the toaster checks for last user to increment a statistic (i suppose), but in this case, the last user is null, which causes a null pointer exception.
[crash-2022-02-26_12.57.38-server.txt](https://github.com/FoundationGames/Sandwichable/files/8146525/crash-2022-02-26_12.57.38-server.txt)
[Where it fails:](https://github.com/FoundationGames/Sandwichable/blob/2d622d1e25c38a631e8454b067fb9c234d7d42d3/src/main/java/io/github/foundationgames/sandwichable/blocks/entity/ToasterBlockEntity.java#L155)

as you can see, here the line contains `if (!world.isClient()) {` and then directly goes on to the player uuid
 easiest way to fix imo would be to just change that line to `if (!world.isClient() && this.lastUser != null) {`

Might be related to #126 , since the logs seem extremely similar, and the stacktraces are basically identical, although i am not 100% sure

**Comment by celophys** [comment]
Same error for me

**Comment by FoundationGames** [comment]
This has been fixed
