### ISSUE TITLE
Read it (problem to enter my server so this mod install on server)

### ISSUE THREAD

**Issue by DarkLight-88** [FoundationGames/Sandwichable#128]
I install last version of  this mod on my server, and it run too, bu when I want go to it, give this error:
https://s6.uupload.ir/files/problem_dr1t.jpg
can any who help to skip this problem?! :I

**Comment by FoundationGames** [comment]
You need the mod installed on your **client** too
The same reason you can't join a 1.18 server with 1.12 or any other version because they don't have the same features
