### ISSUE TITLE
Adding items to a max sized sandwich deletes items

### ISSUE THREAD

**Issue by Bawbby** [FoundationGames/Sandwichable#13]
When the sandwich is of max size, adding more items does nothing but consume your item.
Wondering if you could add a warning like "this sandwich is too tall to add anything else!" and not consume the item.

**Comment by FoundationGames** [comment]
This will be fixed in the next update. Thanks!

**Comment by Bawbby** [comment]
Issue is rather old and the issue has been fixed a while ago. Anyways, thanks!
