### ISSUE TITLE
[bug] Sandwich in sandwich = crash

### ISSUE THREAD

**Issue by StarSomeGamePerson** [FoundationGames/Sandwichable#135]
Happened sometime in Feb 2021, didn't know this was here nor if anyone said anything.

Was in some AOF modpack with this mod, and thought it was a smart idea to put a already made sandwich to a still making sandwich. It allowed it, till I picked it up, then the game crashed. And, tada, every time I tried to open the world it kept crashing every time. Yah, pretty stupid, but curiosity killed the cat

How to reproduce:
no clue as I didn't try to re-create it, most likely just putting a sandwich in a sandwich

**Comment by FoundationGames** [comment]
If you are going to report a bug please test it in the **newest version**. It has been long since patched unless another mod is  causing problems.
