### ISSUE TITLE
Fermenting milk bucket tooltip crash

### ISSUE THREAD

**Issue by emilyploszaj** [FoundationGames/Sandwichable#14]
Hovering over a fermenting milk bucket in the creative inventory (potentially elsewhere) causes a null pointer exception. Using `sandwhichable-v1.0.2--1.15.x.jar` in an unreleased version of All of Fabric 2.

**Comment by FoundationGames** [comment]
That is strange, the bucket is supposed to display a "No Properties" tooltip if its tag is null. I will see if I can implement a fix, since I have not encountered NPEs from hovering over a null bucket.

**Comment by emilyploszaj** [comment]
Ah, I assume it was null because I got it from REI.

**Comment by FoundationGames** [comment]
The tag being null is not an issue, the issue is a tag being present but the actual data not being there.
