### ISSUE TITLE
Can you adopt the new Simplified Chinese translation?

### ISSUE THREAD

**Issue by VAN-192** [FoundationGames/Sandwichable#144]
I noticed that the original translation had a lot of untranslated places in the new version, so I updated the simplified Chinese translation and hope it can be adopted.
[zh_cn.txt](https://github.com/FoundationGames/Sandwichable/files/9311534/zh_cn.txt)

**Comment by FoundationGames** [comment]
Thanks very much, although this would be best suited as a pull request (so that others can review individual lines, and you can be added to the commit history)

**Comment by VAN-192** [comment]
Sorry I don't really understand how github works anymore, so I spent the afternoon learning and submitting pull requests..
