### ISSUE TITLE
Crash when eating a sandwich

### ISSUE THREAD

**Issue by Kasualix** [FoundationGames/Sandwichable#148]
latest.log: 
https://pastebin.ubuntu.com/p/GMmtJV5cvm/
crash report:
https://pastebin.ubuntu.com/p/SMNVycwKgt/

**Comment by Kasualix** [comment]
btw, it is a crazy sandwich
![}H9XD0% CWU`5ZXYQQIW6Q7](https://user-images.githubusercontent.com/110756250/188367675-02f8f141-8900-4c77-8e0d-0168a0fd72df.png)

**Comment by chimericdream** [comment]
I noticed this as well. In my case, it was a more "normal" sandwich, but I was in creative like you are in the screenshot above. In survival, I was able to eat the sandwich fine.
