### ISSUE TITLE
Crash while planting lettuce

### ISSUE THREAD

**Issue by Neubulae** [FoundationGames/Sandwichable#15]
[crash-2020-05-14_17.39.35-server.txt](https://github.com/FoundationGames/Sandwichable/files/4627386/crash-2020-05-14_17.39.35-server.txt)
I suspect it's something to do with Demeter...

**Comment by FoundationGames** [comment]
Demeter breaks all modded crops.

**Comment by Neubulae** [comment]
oof ok
