### ISSUE TITLE
Crop blocks' appendProperties should call super

### ISSUE THREAD

**Issue by liach** [FoundationGames/Sandwichable#16]
Problematic methods:
https://github.com/FoundationGames/Sandwichable/blob/f750f25ef0cdccc95043fbd9bf5473f6f2dab61b/src/main/java/io/github/foundationgames/sandwichable/blocks/LettuceCropBlock.java#L56-L58
https://github.com/FoundationGames/Sandwichable/blob/f750f25ef0cdccc95043fbd9bf5473f6f2dab61b/src/main/java/io/github/foundationgames/sandwichable/blocks/TomatoCropBlock.java#L54-L56
`super.appendProperties(builder);` should be called in both method bodies.

Reason: Wtoll/demeter#13
Similar issue: CottonMC/Epicurean#30

**Comment by FoundationGames** [comment]
Good eye! Will fix.

**Comment by FoundationGames** [comment]
Now that I think about it, this might be the "compatibility issue" with Demeter...

**Comment by liach** [comment]
Yes, these methods theoretically should have super called even if the super method is blank. In other implementations it is more obvious that super should be called like in logs (I think?), but this one here is indeed tricky.

**Comment by FoundationGames** [comment]
This is, unfortunately, not possible since the super method is _**not**_ blank, it actually appends a conflicting IntProperty to the builder, meaning that the two conflict and the game crashes. This means that calling super will not fix anything, instead it will just break the game.

**Comment by Neubulae** [comment]
> This is, unfortunately, not possible since the super method is _**not**_ blank, it actually appends a conflicting IntProperty to the builder, meaning that the two conflict and the game crashes. This means that calling super will not fix anything, instead it will just break the game.

...but while I try appending this to the code, it actually fixes the problem without crashing the game.
And yes since the source is incomplete I have to use something to decompile the jar.
The only problem is the crops don't grow. Maybe that's why your game crashes(hence mine)
