### ISSUE TITLE
Crashes on client

### ISSUE THREAD

**Issue by Neubulae** [FoundationGames/Sandwichable#18]
https://pastebin.com/QCiF5x3W
but it's fine on server, I wonder why

**Comment by Neubulae** [comment]
I deleted modid.mixins.json in the jar and it becomes fine, huh

**Comment by FoundationGames** [comment]
Wow, I did not realize I left that in there... probably because of some issues in the dev environment that I tried to fix with the example mod... The thing is that those mixins should not be loading because they are not defined in the fabric.mod.json...

**Comment by FoundationGames** [comment]
Fixed in 1.1.1
