### ISSUE TITLE
Crash when you click on cheese

### ISSUE THREAD

**Issue by Miros77** [FoundationGames/Sandwichable#21]
[crash-2020-06-07_04.36.32-client.txt](https://github.com/FoundationGames/Sandwichable/files/4741279/crash-2020-06-07_04.36.32-client.txt)

**Comment by FoundationGames** [comment]
Could you describe in detail how to reproduce this issue?

**Comment by Miros77** [comment]
when you click on wheel cheese by basin then crash

**Comment by FoundationGames** [comment]
This may be a compatibility issue because when I tested it, clicking on basins works fine

**Comment by FoundationGames** [comment]
I see the issue. You are using optifine, do not use optifine with mods. It's extremely painful to fix optifine compatibility bugs because sp614x has closed the source for OptiFine.

**Comment by Miros77** [comment]
OK

**Comment by Miros77** [comment]
https://github.com/sp614x/optifine/issues/4058#

**Comment by Miros77** [comment]
click one cheese crash, click on two there is no crash

**Comment by Miros77** [comment]
no OPTIFINE
