### ISSUE TITLE
Invisible Sandwiches in inventory 

### ISSUE THREAD

**Issue by BlaWi** [FoundationGames/Sandwichable#22]
Hello!

Every sandwich i make is invisible in the inventory! I only use sandwichable and the veggie way mod!

**Comment by FoundationGames** [comment]
Might I know what version of Sandwichable / Minecraft you are using?

**Comment by BlaWi** [comment]
I use 1 .16 pre 2 and the first Version of sandwichable for this release 1.1.0

**Comment by FoundationGames** [comment]
You might want to try 1.1.1

**Comment by BlaWi** [comment]
I made a new world with 1.16 pre 5 and version 1.1.1 and everything is fine!
