### ISSUE TITLE
Compatibility request

### ISSUE THREAD

**Issue by DanShu15** [FoundationGames/Sandwichable#26]
We're using the Spice of Fabric mod to make food more valuable on our server (fabric with MC 1.15.2) and I was wondering if there was a way to make sandwiches count as individual food items?
At current, eating an apple sandwich, then bacon, then pork, then fish sandwich all take longer than the previous one to eat, similar to if you ate the same food over and over again.

I'll post a link to this in Spice of Fabric as well, since I'm not sure which side would provide that kind of compatibility - but it'd be sweet if we could :)

Edit-
Just posted more info on Spice of Fabric - but apparently anything used to make a sandwich is now saturated and they can't eat it anymore LOL

Some Console log spam
https://pastebin.com/84H5YARy

**Comment by Miros77** [comment]
I can play on this server

**Comment by DanShu15** [comment]
> I can play on this server

Are you asking to join our server?
If so I can't really accept at the moment, iwe've already got almost 30 testers and more incoming - and we're only in beta with the modpack at the moment. Hopefully when 1.16 drops we'll get all migrated over from 1.15.2 and then we'll fully release the modpack. It's called The Fabric Collection :) keep an eye out for it and we'd love to see you at release :)
In the meantime if you need any help with your modpack you're welcome to find me on the Fabric or All of Fabric discord and shoot me a PM. I'll help if I can :)

**Comment by Miros77** [comment]
How many mods are on the server?

**Comment by DanShu15** [comment]
all together with libraries over 200, so you do need a decent amount of ram both server and client side or you need to restart frequently and log out of the game and start it back up frequently. It's in beta, so the server and client are identical and splitting the mods up into client and server only mods will help, but we're not going to release until 1.16 so I haven't bothered for just testing and making it compatible

**Comment by Miros77** [comment]
I have 4 RAM

**Comment by Miros77** [comment]
:(

**Comment by DanShu15** [comment]
it's worth a shot, I'd do 3gb to your client through MultiMC and I'd go through my mod list and take out absolutely anything you don't need with it's configs. The rest should work fine

**Comment by Miros77** [comment]
can without MultiMC

**Comment by Miros77** [comment]
can just go with mods

**Comment by Miros77** [comment]
?

**Comment by FoundationGames** [comment]
You can put any food in a sandwich, and each food is "consumed" one after the other, so Spice of Fabric modifiers are applied to the foods one by one as their food values are added upon eating the sandwich. Making separate sandwich variations as separate foods would be a bit overpowered with Spice of Fabric in my opinion.

**Comment by DanShu15** [comment]
yea since there's no actual end product I figured that would be the case. If you ever decide to library out the options I'd love to use Sandwichable again! We won't be taking it out, but we'll limit it to the basic sandwiches of 1 food type and the food types you introduced with the mod to make it work properly on our server :)
Thank you anyway, and thank you for the great mod :)

**Comment by DanShu15** [comment]
> can just go with mods

you can do whatever you want with it tbh. You could rename it and release it as your own mod if you'd like. We're in beta with many testers trying to make a modpack and I'm offering it to you if you're interested :)
Change it any way you please, all I've done is make some datapacks and change config files so it works for our server. After that it's up to you :)
Join the fabric or AOF2 or any discord with Dan Shu and send me a PM and you can have a copy

**Comment by DanShu15** [comment]
I'm just offering because I looked at your crashlog and see a number of problems, like outdated API and a mismatch of mod versions. If it would help you not worry about it and just play some Fabric MC then I'm down to help :)
