### ISSUE TITLE
Are bushes trying to grow?

### ISSUE THREAD

**Issue by DanShu15** [FoundationGames/Sandwichable#27]
just curious what this was from

20.06 02:11:02 [Server] Server thread/INFO Cannot get property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{sandwichable:lettuce}

**Comment by FoundationGames** [comment]
That should not be happening, the lettuce crop overrides the default crop age values. Although, I checked, and it seems I forgot to explicitly override it, but it still shouldn't be an issue. If you are using something like Demeter with this mod then I suggest you don't. I will close the issue once I add explicit override annotations in the code.

**Comment by DanShu15** [comment]
I doubt anything works properly with Demeter LOL
It's not any big deal tbh, I just get the occasional weird console message about the integer, typically with cucumbers or bushes, so I was curious :)

**Comment by FoundationGames** [comment]
If it's happening with vanilla crops, it's some other mod messing with everything.

**Comment by DanShu15** [comment]
hmm interesting 
20.06 16:46:36 [Server] Server thread/INFO Cannot get property class_2758{name=age, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7]} as it does not exist in Block{minecraft:beetroots}
This is the vanilla one. if it's not associated then who knows? \o/
Thanks either way :)
