### ISSUE TITLE
Eating spread causes crash with sandwichable-1.1.1-snapshot__1.16-pre2

### ISSUE THREAD

**Issue by Danklor** [FoundationGames/Sandwichable#30]
Platform: MacOS 10.14.6, Java 14.0.1, MultiMC 0.6.11-1370
Minecraft 1.16.1, Fabric loader 0.9.0 build 204

fabric-api-0.15.0+build.379-1.16.1
sandwichable-1.1.1-snapshot__1.16-pre2

No other mods.

Full log attached.

[Eat_spread_and_crash_full.txt](https://github.com/FoundationGames/Sandwichable/files/4959766/Eat_spread_and_crash_full.txt)

**Comment by Danklor** [comment]
This only seems to affect spread that has been obtained with the /give command and without adding a valid spreadType tag.

**Comment by FoundationGames** [comment]
Of course it was an NPE, this will be fixed.. although spreads are not supposed to be used as items, unless you want to put them in item frames/cutting boards for decoration.

**Comment by FoundationGames** [comment]
After some testing, this crash only happens in creative. The NPE was due to the player's hunger manager being null, not the spread type being null.

**Comment by FoundationGames** [comment]
This has been resolved in the latest commit, stay tuned for version 1.1.2's release!
