### ISSUE TITLE
AppleSkin mod does not show the saturation that sandwiches can add

### ISSUE THREAD

**Issue by linzexin022** [FoundationGames/Sandwichable#31]
Hi there, I found AppleSkin mod does not show the saturation that sandwiches can add, so I cannot see clearly how much saturation the sandwiches I made is. Is it because the code doesn't define a prepared sandwich as food (so that AppleSkin mod cannot understand)?

**Comment by FoundationGames** [comment]
Sandwiches are not normal food items. They are foods to the game but they restore no hunger or saturation on their own. When eaten, they apply the effects of every food on the sandwich to you, including hunger and saturation.

**Comment by FoundationGames** [comment]
I'm closing any issues labeled Fixed in Development so I can work on fixing open issues. This issue was fixed in the alpha/beta versions for 1.2.
