### ISSUE TITLE
i placed the cheese that wasnt done back to the basin and one of the cheese crashes me

### ISSUE THREAD

**Issue by frctionless** [FoundationGames/Sandwichable#34]
this is the log
[crash-2020-07-31_12.36.04-client.txt](https://github.com/FoundationGames/Sandwichable/files/5006577/crash-2020-07-31_12.36.04-client.txt)

**Comment by FoundationGames** [comment]
This has been fixed in the latest commit and is yet to come to the latest release.

**Comment by frctionless** [comment]
Ok
