### ISSUE TITLE
[Feature Request] Sliced Golden Carrots

### ISSUE THREAD

**Issue by saltyseadoggo** [FoundationGames/Sandwichable#37]
This is in no way needed, but I thought that, since Golden Carrots are a rather prevalent food item in addition to their potion usage, that giving them a sliced variant created with the Cutting Board to mirror the Sliced Carrot and Sliced Golden Apple could be a neat thing to add.~

**Comment by FoundationGames** [comment]
This is a good idea. Don't know why I didnt think of it.

**Comment by FoundationGames** [comment]
Added!
