### ISSUE TITLE
[Feature Request] Chicken, Cod and Salmon Fillets

### ISSUE THREAD

**Issue by saltyseadoggo** [FoundationGames/Sandwichable#38]
It feels a bit strange placing an _entire roasted chicken or fish, bones and all_ into a sandwich. I would like to suggest allowing raw Chicken, Cod and Salmon to be chopped on the Cutting Board to create raw Chicken, Cod and Salmon Fillets, which, like the preparation of these animals in reality, would be the trimmed chicken breast/fish meat from these animals instead of the entire animal, and could be cooked in the same ways as Pork Cuts. Their values and how many items should be yielded by the chopping are ultimately up to you, but I could see that working like Pork Cuts already do.

**Comment by FoundationGames** [comment]
Then again, it is kinda weird that the player can eat a whole fish, chicken, etc bones and all as well...
But I get the memo, more sliced things!

**Comment by FoundationGames** [comment]
Has been added!
