### ISSUE TITLE
[Gameplay Bug] #29 applies to Cutting Boards and Redstone Toasters as well

### ISSUE THREAD

**Issue by saltyseadoggo** [FoundationGames/Sandwichable#39]
Issue #29, specifically not being able to see sandwiches on Sandwich Tables or cucumbers in Pickle Jars placed by other players, also affects the Cutting Boards and the Redstone Toaster: if player A places something onto the Cutting Board or into the Toaster, player B cannot see it, but can perform the usual interactions such as taking the item off/out or chopping up the item on the Cutting Board. Furthermore, if player A places an item onto a Cutting Board and player B chops it up, the item is still visible on the Board to player A, but is effectively a 'ghost' that can be replaced by other items, and cannot be chopped.

**Comment by FoundationGames** [comment]
See #29
