### ISSUE TITLE
Wheel of Cheese too much saturation

### ISSUE THREAD

**Issue by ClammyMantis488** [FoundationGames/Sandwichable#4]
Is the wheel of cheese supposed to have 63 bars of saturation?
![javaw_inZXtAoAti](https://user-images.githubusercontent.com/25406353/78834383-5b808180-79a3-11ea-9c3f-b593e05a8e2f.png)

**Comment by FoundationGames** [comment]
Thank you for the bug report! No, it's not supposed to have 63 saturation points, that is very strange... I will check myself, but it may be an issue with AppleSkin or whatever mod you are using. In game, try draining your hunger to 19/20 and see if it restores your saturation all the way.

**Comment by FoundationGames** [comment]
Fixed in v1.0.2!
