### ISSUE TITLE
Translated in Russian

### ISSUE THREAD

**Issue by Miros77** [FoundationGames/Sandwichable#42]
[ru_ru.zip](https://github.com/FoundationGames/Sandwichable/files/5120930/ru_ru.zip)

**Comment by FoundationGames** [comment]
Thank you! Please give me a link to your CurseForge profile so I can add you as a translator after the next release.

**Comment by Miros77** [comment]
> Thank you! Please give me a link to your CurseForge profile so I can add you as a translator after the next release.
Ok

https://www.curseforge.com/members/mirosmir/projects

**Comment by FoundationGames** [comment]
(moved to pull request)
