### ISSUE TITLE
Translated in French (and ask for a little tip)

### ISSUE THREAD

**Issue by Water-Kitten** [FoundationGames/Sandwichable#44]
Hello, I saw that someone offered his russian translation, so I wanted to share the french mine, if it can be usefull.

[fr_fr.zip](https://github.com/FoundationGames/Sandwichable/files/5137453/fr_fr.zip)

Also as a beginner at modding, I was wondering how to transform these mods' files, download here, into a functionnal mod after adding some files (like translation ones). I tried something with "gadlew build", but the final .jar doesn't work... (Maybe I did it wrong)

I don't know if I'm undersantable, but if I am, can someone give me some tips to simply recompile this wonderfull mod in a functionnal .jar with a custom translatrion in it, please?

Thank you!

**Comment by Miros77** [comment]
> Hello, I saw that someone offered his russian translation, so I wanted to share the french mine, if it can be usefull.
> 
> [fr_fr.zip](https://github.com/FoundationGames/Sandwichable/files/5137453/fr_fr.zip)
> 
> Also as a beginner at modding, I was wondering how to transform these mods' files, download here, into a functionnal mod after adding some files (like translation ones). I tried something with "gadlew build", but the final .jar doesn't work... (Maybe I did it wrong)
> 
> I don't know if I'm undersantable, but if I am, can someone give me some tips to simply recompile this wonderfull mod in a functionnal .jar with a custom translatrion in it, please?
> 
> Thank you!

run CMD

example

cd C:\Users\Радимир\.gradle\Sandwichable-fabric-1.16.x-dev

then

>gradlew build

**Comment by Miros77** [comment]
try the upper Jar

example
![8](https://user-images.githubusercontent.com/59547044/91589887-23360b80-e963-11ea-8a52-99bcfbac8e96.JPG)

**Comment by FoundationGames** [comment]
Thank you for the translation! It's great to improve the experience for worldwide users. I would have suggested that you submit a pull request, but this should be fine too!

**Comment by FoundationGames** [comment]
To build your translations into a jar, clone or download this repository, add your translation to the src/main/resource/assets/sandwichable/lang folder, and then open a command window in the root directory of the downloaded repo. In that window, run "gradlew build" and it should set up and run gradle and build the project from there. You can find the jar in build/libs.

**Comment by Water-Kitten** [comment]
It works! Thank you so much guys!

And sorry to didn't post it where it deserves to be; what is a "pull request", what it's used for ? (sorry, real noob here x) )

**Comment by Miros77** [comment]
> It works! Thank you so much guys!
> 
> And sorry to didn't post it where it deserves to be; what is a "pull request", what it's used for ? (sorry, real noob here x) )

I have already made and written that this is your translation

**Comment by Miros77** [comment]
> It works! Thank you so much guys!
> 
> And sorry to didn't post it where it deserves to be; what is a "pull request", what it's used for ? (sorry, real noob here x) )

here in the picture
![pull](https://user-images.githubusercontent.com/59547044/91620426-9ad25d80-e998-11ea-9da4-50ebe1d267d1.JPG)

**Comment by Miros77** [comment]
![pull2](https://user-images.githubusercontent.com/59547044/91620714-6b702080-e999-11ea-8246-85d649d923a8.JPG)

**Comment by Miros77** [comment]
![pull3](https://user-images.githubusercontent.com/59547044/91620764-90fd2a00-e999-11ea-9ca3-473ea1c6d88f.JPG)


> It works! Thank you so much guys!
> 
> And sorry to didn't post it where it deserves to be; what is a "pull request", what it's used for ? (sorry, real noob here x) )

![pull3](https://user-images.githubusercontent.com/59547044/91620764-90fd2a00-e999-11ea-9ca3-473ea1c6d88f.JPG)

**Comment by Water-Kitten** [comment]
Thanks Miros! :D

**Comment by Miros77** [comment]
> Thanks Miros! :D

I just wanted to let you know that I will be pushing new features and the translation will need to be updated further, so this will not be merged until the full release of 1.2.

**Comment by Miros77** [comment]
> Thanks Miros! :D

hi can you translate my mod

https://github.com/Miros77/Realistic-Bakery-Products---Fabric

**Comment by Water-Kitten** [comment]
> hi can you translate my mod
> 
> https://github.com/Miros77/Realistic-Bakery-Products---Fabric

Of course ! In exchange can you explain me how to do a pull request where we can put a translation ? I can't find good and simple tutorials on it wich not request a PhD in english xD I really want to know how to use the pull request on GitHub... Thx !

**Comment by FoundationGames** [comment]
(moved to pull request)
