### ISSUE TITLE
[Balance] Pickle Chips seem underpowered for the effort needed to make them

### ISSUE THREAD

**Issue by saltyseadoggo** [FoundationGames/Sandwichable#47]
Pickle Chips require one to farm cucumbers, find a biome compatible with the desalinator to set it up in and fuel it valuable redstone dust (disregarding salty sand), manually convert the cucumbers into pickles, and then chop them, and the reward for this effort is a food item that restores two points of hunger. By comparison, carrots can be farmed, chopped and campfired in any biome and restore three points of hunger, and beetroots work the exact same way and restore four points, at the cost of quantity due to beetroots not dropping multiple crops or being compatible for Fortune. (This is to say nothing of potatoes being compatible with Fortune and able to be smelted or smoked en masse into jacket potatoes that restore five hunger.)

I feel that, for a food that requires either a rare ore or specific biomes and redstone dust to make, as well as the time spent pickling, Pickle Chips should perhaps be a bit more effective as a food. I feel that four hunger points would be the minimum, but five or even six may be appropriate for the extra effort put into them compared to other foods.

Two disclaimers: Firstly, I have not checked the saturation points provided by pickle chips, so it's fully possible that they make up for their low hunger restoration with higher saturation restoration. Secondly, this suggestion is thought of with consuming the pickle chips as a standalone food source, and would need to be balanced as part of sandwiches as well. If either of these cases make the pickle chips balanced as they currently are in your opinion, you can close this issue.~

**Comment by FoundationGames** [comment]
From my own survival experience, I guess this is true... If you aren't near a beach. In my own survival world I started out right next to a beach, mined out some salty sand and got to pickle making quite quickly. But I agree that when living much further away, it's a bit more difficult to get your hands on salt. I may make salt more common somehow...
However I have thought of coming up with a way to add bonuses to sandwiches based on the combinations of foods put together... meaning that a sandwich with onions and jam won't have as good a benefit as one with regular cheese, steak, and pickles...

**Comment by saltyseadoggo** [comment]
We did spawn a fair ways away from the nearest beach or ocean, this is true. Regardless, even if you find salty sand fairly early on, pickle chips still take far more steps to make than the likes of chopped carrot, chopped beetroot or jacket potato, all of which restore more hunger.
Farm potatoes -> Smelt or smoke potatoes _(one furnace/smoker can process 64 at once and runs on its own)_ -> Jacket Potato which restores five hunger points
Farm cucumbers -> Find salt -> Pickle cucumbers _(one jar can process four at once, runs on its own)_ -> Chop pickles _(manually, one at a time)_ -> Pickle Chips which restore one hunger point
I just felt like, after making some pickles of my own, that they don't reward the effort it takes to make them very well when Cooked Chopped Carrot/Beetroot and Jacket Potato take less steps and restore more hunger.
If you do add a system that detects "proper" sandwiches to give better benefits, however, the pickle chips could make themselves clear as being more effective as part of a sandwich than eaten on their own.
In terms of making salt more common, you could always have the Sandwich Maker villager profession sell it. If you aren't fazed by modifying base-game villagers, the Butcher could also be a good fit, as butchers use salt to preserve their meats, and this would give them a better niche compared to their relative uselessness in the base game.

**Comment by FoundationGames** [comment]
This has been resolved, pickle chips have a fullness bonus of 4 (highest so far) and salt is made faster in a desalinator.
