### ISSUE TITLE
Cheese dupe bug with basin

### ISSUE THREAD

**Issue by copygirl** [FoundationGames/Sandwichable#48]
**Minecraft:** `1.16.2`
**Fabric API:** `0.20.1+build.401`
**Sandwichable:** `1.1.2`

After placing a cheese slice into a basin you can get back a whole wheel of cheese.

**Comment by FoundationGames** [comment]
This... is confounding??? I have no idea how I would make that kind of mistake but thanks for letting me know!

**Comment by FoundationGames** [comment]
I looked at the code... This has been a bug since 1.0.2 and you have just found it!

**Comment by copygirl** [comment]
It was easy to overlook. Who would right click a slice on the basin anyway, other than by accident? (Which is what I did.)
