### ISSUE TITLE
Cant fill jar with water for pickle cucumbers

### ISSUE THREAD

**Issue by miblachit** [FoundationGames/Sandwichable#59]
And make possibility to cut normal cucumber

**Comment by FoundationGames** [comment]
You need to place down a jar and right-click it with a water bucket to fill it. Normal cucumbers cannot be sliced, you need to pickle them to slice them. If this solves your issue then I will close it.

**Comment by miblachit** [comment]
The problem was with wooden buckets, and salt from another mod. Not your fault, sorry.

**Comment by FoundationGames** [comment]
Thanks for letting me know!
