### ISSUE TITLE
planting tomatoes and letting them grow crashes server

### ISSUE THREAD

**Issue by systemm0** [FoundationGames/Sandwichable#6]
as the title says.

here is the logs

[HERE](https://pastebin.com/1rLYaqXF)

**Comment by FoundationGames** [comment]
I experienced this for myself, in AOF2. You seem to be using Lithium, what other mods are you using? Since in AOF2, I have experienced this with other modded crops.

**Comment by systemm0** [comment]
yeah, AOF2. I posted it on theirs.. and they said post it on yours.. but I think they figured out it might be a conflict with the Demeter mod. @ak9official

**Comment by FoundationGames** [comment]
Yes, it was Demeter. I believe an issue may have been posted.
