### ISSUE TITLE
Overworld Cutting Boards can't be used as fuel

### ISSUE THREAD

**Issue by saltyseadoggo** [FoundationGames/Sandwichable#60]
Expected Behaviour
The Oak, Spruce, Birch, Jungle, Acacia and Dark Oak cutting boards can be used as fuel in a furnace, mirroring all of the blocks made with these wood types in vanilla Minecraft.
Actual Behaviour
The Oak, Spruce, Birch, Jungle, Acacia and Dark Oak cutting boards cannot be used as fuel in a furnace.

Given that the Crimson and Warped woods cannot be used as furnace fuel due to being fireproof, their cutting boards shouldn't burn either, so their behaviour makes sense.~

**Comment by FoundationGames** [comment]
Furnace fuels are somewhat hardcoded, but it shouldn't be too difficult to implement for the next update. Thanks!

**Comment by FoundationGames** [comment]
Fortunately, Fabric API had me covered. Will be resolved in 1.1.3!

**Comment by FoundationGames** [comment]
I'm closing any issues labeled Fixed in Development so I can work on fixing open issues.
