### ISSUE TITLE
Salty sand cannot be gathered with Silk Touch

### ISSUE THREAD

**Issue by saltyseadoggo** [FoundationGames/Sandwichable#62]
**Expected Behaviour**
Being a block that drops something other than itself, salty sand would be able to be obtained if a player breaks it with any tool enchanted with Silk Touch.
**Actual Behaviour**
Salty sand still drops salt rocks and regular sand when broken by any tool enchanted with Silk Touch. This was tested with a Silk Touch pickaxe, which would be able to obtain the likes of grass blocks, podzol and mycelium.

**Comment by FoundationGames** [comment]
Thanks for the issue, this will be fixed.

**Comment by FoundationGames** [comment]
I also noticed that fortune doesn't work on salty sand, this will also be changed.

**Comment by FoundationGames** [comment]
I'm closing any issues labeled Fixed in Development so I can work on fixing open issues.
