### ISSUE TITLE
[Game CRASH] Eating sandwich -> java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by Slexom** [FoundationGames/Sandwichable#75]
**Description**
Game crashed on eating sandwich (Toasted bread + Mayonnaise + Berry Jam + Toasted bread) 
It must be some rare bug, because this isn't the first sandwich I use on 1.2-beta1

**Crash Log**
https://gist.github.com/Slexom/c82e5dbe4c3e17821e57042969c1a5b1

**Comment by FoundationGames** [comment]
That's really strange... I'll test for myself. Are you sure the crash happens when you eat the sandwich? The problem area seems to be where the item _name_ is calculated, not where when the sandwich is eaten.

**Comment by FoundationGames** [comment]
I was unable to reproduce this bug. I'll keep this issue open for a week and close if I don't get a bit more clarification. Thanks for the contribution, though!

**Comment by Slexom** [comment]
If i correctly remember my steps before it happened was:
 - open inventory
 - move sandwich from inventory to first slot
 - goes to bed and sleep
 - wake up
 - eat the sand*CRASH* XD
Nothing related maybe.
I'm unable to reproduce it too, when reloaded the game and eat it all goes fine. After that, and before, I've used sandwiches without any issue.
You said the problem seems to be related to item name calculation, could it be something with Italian locales? Or simply a random bug occurred somewhere and game crashed at that point.

**Comment by Snoe0** [comment]
For me I get the same error when I make sandwiches, not when I eat them.

**Comment by FoundationGames** [comment]
Unable to confirm this issue
