### ISSUE TITLE
[Gameplay Bug] Water not properly dispensed from dispensers

### ISSUE THREAD

**Issue by FoundationGames** [FoundationGames/Sandwichable#78]
**Description**
Water buckets don't place the actual fluid down when dispensed, instead dispense item

**How To Reproduce**
Dispense a water bucket with a dispenser, as if you wanted to place the fluid

**Expected Behavior**
The water fluid to be placed down by the dispenser

**Media**
None

**Comment by dandin87** [comment]
AoF 3 v2.6.1 Here are the relevant blame reports for this. Not sure if it applies to all of these, but these are the ones involving buckets below, and here is a link to the full list. https://paste.lucko.me/w30q14HHaO
[00:10:38] [main/ERROR]: 
****************** Blame Extra Info Report 1.16.4-2.4.1 ******************
   Ignore this unless item behavior aren't working with Dispensers.
  Dispenser Behavior overridden for minecraft:milk_bucket
  New behavior: io.github.foundationgames.sandwichable.Sandwichable$2
  Old behavior: net.minecraft.class_2347
  Registration done at: 
    io.github.foundationgames.sandwichable.Sandwichable.onInitialize(Sandwichable.java:162)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)

[00:10:38] [main/ERROR]: 
****************** Blame Extra Info Report 1.16.4-2.4.1 ******************
   Ignore this unless item behavior aren't working with Dispensers.
  Dispenser Behavior overridden for sandwichable:fermenting_milk_bucket
  New behavior: io.github.foundationgames.sandwichable.Sandwichable$2
  Old behavior: io.github.foundationgames.sandwichable.Sandwichable$1
  Registration done at: 
    io.github.foundationgames.sandwichable.Sandwichable.onInitialize(Sandwichable.java:163)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)

[00:10:38] [main/ERROR]: 
****************** Blame Extra Info Report 1.16.4-2.4.1 ******************
   Ignore this unless item behavior aren't working with Dispensers.
  Dispenser Behavior overridden for minecraft:bucket
  New behavior: io.github.foundationgames.sandwichable.Sandwichable$$Lambda$5953/1540374453
  Old behavior: net.minecraft.class_2357$9
  Registration done at: 
    io.github.foundationgames.sandwichable.Sandwichable.onInitialize(Sandwichable.java:164)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)

[00:10:38] [main/ERROR]: 
****************** Blame Extra Info Report 1.16.4-2.4.1 ******************
   Ignore this unless item behavior aren't working with Dispensers.
  Dispenser Behavior overridden for minecraft:bucket
  New behavior: io.github.foundationgames.sandwichable.Sandwichable$$Lambda$5954/100373422
  Old behavior: io.github.foundationgames.sandwichable.Sandwichable$$Lambda$5953/1540374453
  Registration done at: 
    io.github.foundationgames.sandwichable.Sandwichable.onInitialize(Sandwichable.java:175)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)

[00:10:38] [main/ERROR]: 
****************** Blame Extra Info Report 1.16.4-2.4.1 ******************
   Ignore this unless item behavior aren't working with Dispensers.
  Dispenser Behavior overridden for minecraft:water_bucket
  New behavior: io.github.foundationgames.sandwichable.Sandwichable$$Lambda$5955/138954535
  Old behavior: net.minecraft.class_2357$8
  Registration done at: 
    io.github.foundationgames.sandwichable.Sandwichable.onInitialize(Sandwichable.java:187)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
    net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
