### ISSUE TITLE
[Gameplay Bug] Water source not output by dispenser with water buckets in inventory.

### ISSUE THREAD

**Issue by irunatbullets** [FoundationGames/Sandwichable#79]
**Description**
When you add water buckets to a dispenser and apply a redstone signal the dispenser outputs the bucket of water item (like the dropper), rather than outputting a water source. 

**How To Reproduce**
Make a dispenser,
Put a water bucket inside.
Put a button on top.
Press the button.

**Expected Behavior**
Pressing a button should output a water source block in front of the dispenser. Pressing the button again should remove the water source and return it to the bucket inside the the dispenser.

**Additional information**
Using this mod in AOF3 2.6.1. Removing sandwichable restores vanilla behavior.

**Comment by FoundationGames** [comment]
This issue is a duplicate.
