### ISSUE TITLE
stacked sandwiches consume all at once

### ISSUE THREAD

**Issue by BBftw** [FoundationGames/Sandwichable#8]
a stack of sandwiches will be consumed in one go if it is eaten from.

**Comment by FoundationGames** [comment]
That is not entirely true, the issue is that consuming a stack of sandwiches will move it to a different slot and not even decrement the amount. Thanks for letting me know, though.

**Comment by FoundationGames** [comment]
Never mind that, you're right. If there is no available slot, it seems to just disappear.

**Comment by FoundationGames** [comment]
Fixed in v1.0.2!
