### ISSUE TITLE
[Game CRASH] Sandwich made with second sandwich causes crash

### ISSUE THREAD

**Issue by ScidaJ** [FoundationGames/Sandwichable#80]
**Description**
Making a sandwich with another sandwich causes game crash on creation and on world load

**Steps to Reproduce**
Step 1.) Make a sandwich
Step 2.) Create a second sandwich with the first as an ingredient

**Crash Log**
https://gist.github.com/jrs8979/06ecd8f9d45ba1f28c6597c18f6a41d4

**Comment by FoundationGames** [comment]
This has been fixed in development, and the fix will be released in the next beta version.

**Comment by imreallybadatnames** [comment]
I made another solution which actually renders that kind of sandwich properly. Working on angles right now, because all items are rotated 90 degrees and sandwiches are already correctly rotated.

**Comment by FoundationGames** [comment]
Issue has been fixed along with a way to properly put sandwiches within sandwiches. Thanks for the report!
