### ISSUE TITLE
[Game CRASH] Crash upon loading (tooltips loading too early)

### ISSUE THREAD

**Issue by Lucipo** [FoundationGames/Sandwichable#83]
**Description**
crashes upon loading 

**Steps to Reproduce**
get my mods
launch game
it crashes!

**Crash Log**
[crash-2021-02-21_20.44.00-client.txt](https://github.com/FoundationGames/Sandwichable/files/6019775/crash-2021-02-21_20.44.00-client.txt)

**Comment by FoundationGames** [comment]
(was fixed in an earlier version, late response)
