### ISSUE TITLE
[Request] Is Salty Sand supposed to be in Terrestria's Lush Desert?

### ISSUE THREAD

**Issue by saltyseadoggo** [FoundationGames/Sandwichable#87]
**Description**
[Terrestria's](https://github.com/TerraformersMC/Terrestria) *Lush Desert* biome (`terrestria:lush_desert`) has salty sand generate in it when the mod is loaded alongside Sandwichable. Given that salty sand doesn't appear to generate in vanilla deserts, and also doesn't generate in the mod's other sandy biomes such as the *Canyon* variants, I wasn't sure if this is intentional or not.

**Problem or Reasoning**
I would like you to take a brief look at this biome and determine whether you believe salty sand should generate in it, as this is your creative vision, of course. I have some pictures of it down below, and you can explore it for yourself if you load the mod.

**How it will work**
If you determine that salty sand makes sense in this biome, great! Nothing has to change. If not, then you could look into why Sandwichable has deemed this particular biome as worthy of salty sand- be it internal biome values like temperature or such- and potentially reevaluate them to resolve this and potentially other similar mod conflicts.

**Media**
![2021-03-03_12 33 07](https://user-images.githubusercontent.com/69029346/109869493-c707b900-7c1d-11eb-87ba-cca629127209.png)
![2021-03-03_12 40 42](https://user-images.githubusercontent.com/69029346/109869496-c838e600-7c1d-11eb-892d-e02ed32af4f8.png)
![2021-03-03_12 40 48](https://user-images.githubusercontent.com/69029346/109869497-c96a1300-7c1d-11eb-94cb-357a4eb65912.png)

**Comment by FoundationGames** [comment]
Salty sand generates in biomes categorized as `beach` or `ocean`. Terrestria has put this biome in one of these categories, so salty sand is generating in it. You'd have to ask them if this categorization is intentional or not. Thanks for the contribution!

Closed - Works as Intended
