### ISSUE TITLE
Support the harvest:seeds item tag

### ISSUE THREAD

**Issue by sargunv** [FoundationGames/Sandwichable#9]
https://github.com/TehNut/Harvest/blob/1.14_fabric/src/main/resources/data/harvest/tags/items/seeds.json

This is used for [SimpleHarvest](https://www.curseforge.com/minecraft/mc-mods/simpleharvest) to know which item is the seed in the crop item drops.

**Comment by FoundationGames** [comment]
will do in next update!

**Comment by Leeo97one** [comment]
Are u sure about that?
