### ISSUE TITLE
[Gameplay Bug] Weird salt lake generation

### ISSUE THREAD

**Issue by sleepy-evelyn** [FoundationGames/Sandwichable#97]
**Description**
Salt lake generation seems very derpy and doesn't seem to properly take into account other late generated features within the world. Some images of this weird generation are provided below. It seems to also conflict with AE2 meteors pretty badly. Happens on https://github.com/The-Tiny-Taters/TTTM-AOF which is basically AOF3 but with some additional mods ontop running currently on version 2.7.1

**How To Reproduce**
Fly around the world a bit and have a look for some salt lakes

**Expected Behavior**
Better placement of the features

**Media**

**AE2 meteor overlapping generation**
![image](https://user-images.githubusercontent.com/46009144/116003360-7f862380-a5f5-11eb-8bd1-6730a0d16504.png)

**Chunk cutting into the generation**
![Image](https://i.imgur.com/BW5BesU.jpg) and ![Image](https://i.imgur.com/2UJ0xxX.jpg)

**Comment by FoundationGames** [comment]
If a meteor crashed into the earth nearby a salt lake, _what would you expect to happen to the salt lake?_
As far as I can tell generation is working exactly as intended with the salt lakes generating on the previous step compared to the meteors. The salt lake has been properly destroyed by the meteor.
As for the cut off bits of water, that is to be expected when a water body generates above sea level and is generated over by a feature as large as a meteor crater.

**Comment by sleepy-evelyn** [comment]
Whoops I forgot to include the last image. Apologies
This seems to show the lake generating on-top of the meteor

https://media.discordapp.net/attachments/814452859273216070/835626569426010183/2021-04-24_20.png?width=2560&height=1496

**Comment by sleepy-evelyn** [comment]
This seems at least on first glance to be kind of a joint issue anyway though, it seems to happen very frequently however, I mean these 3 images are from just about 15 minutes of flying around so maybe AE2 meteor generation could be considered and it could avoid being placed near them. I don't know enough worldgen though so i'm not sure how easy this would be or if it's even possible

**Comment by FoundationGames** [comment]
That last image is a result of chunk generation order, a vanilla bug i cannot fix.
Press F3+G and see if a chunk boundary fits into that slice taken out of the salt pool, it most likely will.

However the bigger issue I notice with this is that salt pools seem to choose to generate right next to AE2 meteors. I feel like this could be caused by the exact same rule that causes diamonds (pre-1.18) to generate directly offset to clay blobs in swamps. The two features likely use the same decorator with extremely similar configurations.

**Comment by sleepy-evelyn** [comment]
Agreed yeah your explanation makes more sense and yes the last image splits exactly at the chunk border so that's our end. Think threaded anvil chunk storage must have been having a field day.

**Comment by sleepy-evelyn** [comment]
Couldn't reproduce after searching for features for about 30 minutes
